version: '3'
services:
  minigrid:
    build:
      context: ../
    ports:
      - "8889:8889"
    command: ./dev/run.sh --db_host=db --redis_url=redis://redis:6379/0
    volumes:
      - ../:/minigrid-server
    user: root
    depends_on:
      - redis
      - db
  db:
    image: postgres:11.1
    environment:
      POSTGRES_DB: minigrid
  redis:
    image: redis:5.0
