version: '2'
services:
  minigrid:
    build:
      context: ../
    ports:
      - "8889:8889"
    command: ./dev/run.sh --minigrid_port=8889 --minigrid_website_url=http://localhost:8889 --db_host=db --redis_url=redis://redis:6379/0
    volumes:
      - ../:/minigrid-server
    user: root
    depends_on:
      - redis
      - db
  db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: minigrid
  redis:
    image: redis:3.2
