version: '3.3'
services:
  minigrid:
    build:
      context: ../
    ports:
      - "8889:8889"
    command: ./dev/run.sh --db_host=db --redis_url=redis://redis:6379/0
    volumes:
      - ../:/minigrid-server
    user: root
    depends_on:
      - redis
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: minigrid
      POSTGRES_HOST_AUTH_METHOD: "trust"
  redis:
    image: redis:6.2.5
