version: '2'
services:
  minigrid:
    image: selcolumbia/minigrid-server:0.2.2
    command: ./prod/run.sh --db_host=db --redis_url=redis://redis:6379/0 --minigrid-website-url=https://www.example.com
    depends_on:
      - redis
      - db
  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_DB: minigrid
  redis:
    image: redis:3.2.5
  nginx:
    image: nginx:1.11.6
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp:/tmp
      - /var/www
    depends_on:
      - minigrid
