name: full minigrid tests

on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2
      # setup latest firefox version
      - name: Setup latest firefox
        uses: browser-actions/setup-firefox@latest
      # setup database
      - name: create the minigrid database
        run: |
          sudo apt-get install postgresql-13 libpq-dev
          sudo service postgresql start
          psql -U postgres -c 'create database minigrid;'
      # sets up python
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # install python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev/requirements.txt
          pip install coveralls
      - name: Analysing the code with flake8
        run: |
          flake8 .
      - name: Analysing the code with pydocstyle
        run: |
          python3 -m pydocstyle .
      - name: install xvfb
        run: sudo apt-get install xvfb
      - name: run xvfb for python tests
        run: xvfb-run --server-args="-screen 0, 1280x1280x16" tests/python/coverage_run.sh
