name: full minigrid tests

on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2
      # setup latest firefox version
      - name: Setup latest firefox
        uses: browser-actions/setup-firefox@latest
      # setup database
      - name: Install postgresql
        run: |
          sudo apt-get install postgresql-13 libpq-dev
          sudo service postgresql start
          pg_isready
      - name: Change from peer to md5 authentication
        run: |
          sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/13/main/pg_hba.conf
          sudo service postgresql@13-main restart
      - name: create the minigrid database
        run: |
          psql -U postgres -c 'create database minigrid;'
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev/requirements.txt
          pip install -r requirements.txt
          pip install coveralls
      - name: Set up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install node dependencies
        run: |
          npm install
          node node_modules/webpack/bin/webpack.js --mode=production
      - name: Analysing the code with flake8
        run: |
          flake8 .
      - name: Analysing the code with pydocstyle
        run: |
          python3 -m pydocstyle .
      - name: install xvfb
        run: sudo apt-get install xvfb
      - name: run xvfb for python tests
        run: xvfb-run --server-args="-screen 0, 1280x1280x16" tests/python/coverage_run.sh
